apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advert-enrich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NULP-AI-Enterprise/enrich_db_new
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: advert-enrich
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
